### ISSUE TITLE
Ant Media server communication with LiveVideoBroadcaster Android App

### ISSUE THREAD

**Issue by ozankonur** [ant-media/LiveVideoBroadcaster#10]
Hi, I build & start the ant-server (start.bat windows) then I start to subscribe demo (http://127.0.0.1:5080/demos/simpleSubscriber.html) and it started to listen "rtmp://localhost/oflaDemo".  On the other hand, I typed to android app ( RTMP_BASE_URL = "rtmp://myMachineIP/oflaDemo") and I build the android app and run it. But android app doesn't start to live streaming. Is this way not true Dear Ahmet ?

**Comment by davutcavdar** [comment]
Hi,

Your RTMP address should looks like as : "rtmp://yourMachineIP/applicationName/streamIP"

**Comment by mekya** [comment]
do you have any update Dear @ozankonur  :) ?

**Comment by TheRokon** [comment]
Hi everything ok. I connect it with nginx rtmp server thank you Davut and Ahmet :)

**Comment by ozankonur** [comment]
Hi, everything ok I connect app with nginx. Thank you Davut and Ahmet :)

**Comment by mekya** [comment]
We can help you more if you use Ant Media Server ;) 
Moreover you can make some contributions in the product by giving your feedbacks. Last but not least, we can event give you the enterprise edition for free ;)

**Comment by ozankonur** [comment]
I try it with simple demo project. Currently, I am using this client https://github.com/pedroSG94/rtmp-rtsp-stream-client-java with Nginx - rtmp server.. They are working good. If the scope of project grows, then we can take a decision, thank you :)

**Comment by saikiran143** [comment]
where i can find start.bat in windows. How to execute it.

**Comment by abhilashi22** [comment]
I don't see any start.bat file. Can't i set it up on Windows?

**Comment by mekya** [comment]
It works on Linux(Ubuntu) and Mac. It does not work on Windows. 

You may use virtualization to run it on top of windows.

**Comment by hmskhan** [comment]
How to run start.sh file in windows @mekya

**Comment by mekya** [comment]
One of our team mates publish a blog post about it. Actually it is running about virtual machine in Windows.  Check it out. 
https://antmedia.io/ant-media-server-windows/

Closing this issue. Please reopen if you are not ok with that.
