### ISSUE TITLE
Live streaming not start when use rtmps live server in place of Red5 local server

### ISSUE THREAD

**Issue by Anjalitripathi** [ant-media/LiveVideoBroadcaster#11]
I have successfully run the app using Red5 local server. But I am not able to run app using rtmps AMS server url. When I hit the start broadcasting button live streaming not start. 

One more thing I notice that live streaming is working only when local server and android phone are on same network.

**Comment by davutcavdar** [comment]
Hi,

Have you configured certificate settings for RTMS?

**Comment by nswarnkar** [comment]
I tried this too on RTMPS, it throws error that unable to connect, though  I can play video gstreamer.
For RTMP, it does not compain.

**Comment by mekya** [comment]
Issues tab will be closed for this project. Please submit your issues on https://github.com/ant-media/Ant-Media-Server
