### ISSUE TITLE
How to have latency time less than 200 ms and increase camera quality.

### ISSUE THREAD

**Issue by Anjalitripathi** [ant-media/LiveVideoBroadcaster#12]
We are using RTMP based AMS(Adobe Media Server). Live streaming is delay by 30 sec. How can we improve this. We want to achieve max delay of 200 ms(latency). 

Any help appreciated.

**Comment by davutcavdar** [comment]
Hi,

Does your solution work based on peer-to-peer or 1 to n broadcasting principle?

**Comment by Anjalitripathi** [comment]
It works on 1 to n broadcasting principle.

**Comment by davutcavdar** [comment]
You can decrease your delay to 2-3 sec instead of 30 sec by using our RTMP based solution (SDK).

**Comment by Anjalitripathi** [comment]
Please provide me your sdk details.

**Comment by davutcavdar** [comment]
Please follow the steps: https://github.com/ant-media/LiveVideoBroadcaster/blob/master/README.md

**Comment by Anjalitripathi** [comment]
The same sdk we are using. but getting around 30 seconds delay.

**Comment by davutcavdar** [comment]
This delay is probably about your Adobe Server configurations.

Could you implement our media server (Ant Media Server)? https://github.com/ant-media/Ant-Media-Server/blob/master/README.md 

Our mobile SDK is tested on Ant Media Server and used by several projects efficiently

**Comment by Anjalitripathi** [comment]
We can't say it is a server configuration issue, because when we use adobe app for live streaming on same server then latency time is around 5 second. But in android app it is too much high.

**Comment by mekya** [comment]
Is it possible to let us try your server and find out what causes the latency in android app?

If yes, you can send details in e-mail mekya at antmedia dot io

**Comment by mekya** [comment]
Closing this issue for the inactivity. Please reopen it if you are still having this problem.
