### ISSUE TITLE
Nothing streams, button doesn't toggle to "stop" either.

### ISSUE THREAD

**Issue by ishandutta2007** [ant-media/LiveVideoBroadcaster#14]
I entered stream name as 'a' then tapped "Start Broadcasting"
Nothing streams, button doesn't toggle to "stop" either.
I have put log in all methods of activity.Here is how it looks.

> I/ActivityManager(  954): START u0 {cmp=io.antmedia.android.livevideopublisher/io.antmedia.android.liveVideoBroadcaster.LiveVideoBroadcasterActivity} from uid 10139 on display 0
> D/LiveVideoBroadcasterActivity(25843): ServiceConnection:onCreate
> D/LiveVideoBroadcasterActivity(25843): ServiceConnection:onStart
> D/LiveVideoBroadcasterActivity(25843): ServiceConnection:onServiceConnected
> I/ActivityManager(  954): Displayed io.antmedia.android.livevideopublisher/io.antmedia.android.liveVideoBroadcaster.LiveVideoBroadcasterActivity: +180ms
> I/Timeline(  954): Timeline: Activity_windows_visible id: ActivityRecord{340bc084 u0 io.antmedia.android.livevideopublisher/io.antmedia.android.liveVideoBroadcaster.LiveVideoBroadcasterActivity t1044} time:690259190
> D/LiveVideoBroadcasterActivity(25843): ServiceConnection:toggleBroadcasting
> D/LiveVideoBroadcasterActivity(25843): ServiceConnection:toggleBroadcasting:StartingRecording
> D/LiveVideoBroadcasterActivity(25843): ServiceConnection:toggleBroadcasting:ConnectingLiveVideoBroadcaster
> D/LiveVideoBroadcasterActivity(25843): ServiceConnection:toggleBroadcasting:onPreExecute

After a long gap (3-4 mins).

> 
> D/LiveVideoBroadcasterActivity(25843): triggerStopRecording
> D/LiveVideoBroadcasterActivity(25843): ServiceConnection:toggleBroadcasting:doInBackground:rtmp://192.168.43.168/vod/a
> D/LiveVideoBroadcaster(25843): startBroadcasting
> W/LiveVideoBroadcaster(25843): Camera should be opened before calling this function
> D/LiveVideoBroadcasterActivity(25843): ServiceConnection:toggleBroadcasting:doInBackground:rtmp://192.168.43.168/vod/a
> D/LiveVideoBroadcaster(25843): startBroadcasting
> W/LiveVideoBroadcaster(25843): Camera should be opened before calling this function
> D/LiveVideoBroadcasterActivity(25843): ServiceConnection:toggleBroadcasting:doInBackground:rtmp://192.168.43.168/vod/a
> D/LiveVideoBroadcaster(25843): startBroadcasting
> W/LiveVideoBroadcaster(25843): Camera should be opened before calling this function
> D/LiveVideoBroadcasterActivity(25843): ServiceConnection:toggleBroadcasting:doInBackground:rtmp://192.168.43.168/vod/a
> D/LiveVideoBroadcaster(25843): startBroadcasting
> W/LiveVideoBroadcaster(25843): Camera should be opened before calling this function
> D/LiveVideoBroadcasterActivity(25843): ServiceConnection:toggleBroadcasting:doInBackground:rtmp://192.168.43.168/vod/a
> D/LiveVideoBroadcaster(25843): startBroadcasting
> W/LiveVideoBroadcaster(25843): Camera should be opened before calling this function
> D/LiveVideoBroadcasterActivity(25843): ServiceConnection:toggleBroadcasting:doInBackground:rtmp://192.168.43.168/vod/a
> D/LiveVideoBroadcaster(25843): startBroadcasting
> W/LiveVideoBroadcaster(25843): Camera should be opened before calling this function
> D/LiveVideoBroadcasterActivity(25843): ServiceConnection:toggleBroadcasting:onPostExecute:false
> D/LiveVideoBroadcasterActivity(25843): triggerStopRecording
> D/LiveVideoBroadcasterActivity(25843): ServiceConnection:toggleBroadcasting:onPostExecute:false
> D/LiveVideoBroadcasterActivity(25843): triggerStopRecording
> D/LiveVideoBroadcasterActivity(25843): ServiceConnection:toggleBroadcasting:onPostExecute:false
> D/LiveVideoBroadcasterActivity(25843): triggerStopRecording
> D/LiveVideoBroadcasterActivity(25843): ServiceConnection:toggleBroadcasting:onPostExecute:false
> D/LiveVideoBroadcasterActivity(25843): triggerStopRecording
> D/LiveVideoBroadcasterActivity(25843): ServiceConnection:toggleBroadcasting:onPostExecute:false
> D/LiveVideoBroadcasterActivity(25843): triggerStopRecording
> D/LiveVideoBroadcasterActivity(25843): ServiceConnection:toggleBroadcasting:onPostExecute:false
> D/LiveVideoBroadcasterActivity(25843): triggerStopRecording
> D/LiveVideoBroadcaster(25843): onResume complete: io.antmedia.android.broadcaster.LiveVideoBroadcaster$7@263271f9
> D/LiveVideoBroadcasterActivity(25843): ServiceConnection:toggleBroadcasting:doInBackground:rtmp://192.168.43.168/vod/a
> D/LiveVideoBroadcaster(25843): startBroadcasting
> 

But still nothings gets broadcasted.

**Comment by mekya** [comment]
Hi,
Are you sure you set up server address correctly and server is running?

Regards,
A. Oguz

**Comment by ishandutta2007** [comment]
Hey,
Where are the configuration steps. I realized the server runs at http://127.0.0.1:5080/
How will my android app know my mac's IP?

**Comment by mekya** [comment]
If you have a public ip then there should be no problem. 
5080 is the port address of http server. It is not used in live stream publishing

Two things come to my mind. 

This address 202.142.99.205. Is your server's real public ip address? May I test this ip to publish live stream? 

For live streams, 1935 port is used. Are you sure  the port 1935 is open?

**Comment by ishandutta2007** [comment]
yes this is my public ip 202.142.99.205
and my server is running.
ishandutta2007@MacBook-Pro:~/Downloads$ `netstat -vanp tcp | grep 1935`
tcp4       0      0  *.1935                 *.*                    LISTEN      131072 131072   4229      0

**Comment by ishandutta2007** [comment]
My whatsapp is +91-9952917263

**Comment by mekya** [comment]
Closing this issue. As I remember we had conversation on whatsapp.

Please re-open it if you are still having the same problem.
