### ISSUE TITLE
Live stream not playing on swf flash player on browser.

### ISSUE THREAD

**Issue by Anjalitripathi** [ant-media/LiveVideoBroadcaster#15]
I have a swf player which plays the rtmp based live stream on browser. I have tested browser video player with following url. This video is playing on the browser player.
(rtmp://184.72.239.149/vod/mp4:bigbuckbunny_1500.mp4). 
But the live stream url we created from this sample is not working on swf player. When I hit this url on safari browser than video is playing on vlc media player only.

What is the file format of video that is created using the sample app. I assume it is other than mp4. Where to change the video file format to mp4 in this sample?

**Comment by mekya** [comment]
Hi @Anjalitripathi ,

Live streams are FLV format in RTMP protocol. VoD streams can be in MP4 or FLV.  MP4 format is not suitable for live streams.  RTMP protocol can be used both VoD and Live streams as well.

I mean if you plan to play a live stream, do not specify any mp4 in url.

**Comment by mekya** [comment]
Closing this issue for the inactivity. Please re-open it if you are still having this issue.
