### ISSUE TITLE
[Question] Can we adjust broadcast according to network condition on the go?

### ISSUE THREAD

**Issue by karanatwal** [ant-media/LiveVideoBroadcaster#2]
Hi .. I didn't test your sdk yet , I have a question can we adjust fps/or quality of video according to internet connection Live ? like fb or youtube does eg. while broadcasting live video over rtmp url if network condition goes worse decrease quality of video and if network become fast , increase quality .Sorry for bad english.

**Comment by davutcavdar** [comment]
Hello,

Adaptive bit rate option is provided with Enterprise edition of Ant Media
Server. You can get more information from link :
http://antmedia.io/enterprise/

Best Regards,

Ant Media

**Comment by mekya** [comment]
Just let me add to @davutcavdar response. On the watcher side, @davutcavdar is right. 

On the publisher side while using this SDK,  if network condition is not good enough, we firstly decrease frame per second. As I remember, fps lower limit is about 12-15 fps. if there is still latency in the network, we start to decrease the quality. It generally covers most of the network conditions.

**Comment by karanatwal** [comment]
@mekya If is it so , i would like to test it for streaming video to facebook now and will tell you wether it works or not by today. Thanx

**Comment by karanatwal** [comment]
@mekya I tested this code by putting facebook rtmp ,but it is returning false :(

**Comment by mekya** [comment]
I have just tested and it is working. Are you sure you have written the rtmp url correctly?

Secondly, what is your device? I have just commit a fix to my local repo but not push the github yet. Some specific [device](http://www.gsmarena.com/samsung_galaxy_grand_neo-5958.php)'s chipset is different than most of the other devices. Fortunately, I think Iatest commit will be expected to support all this kind of devices. 


![screen shot 2017-08-17 at 10 40 00](https://user-images.githubusercontent.com/3456251/29401102-88ff64f0-8338-11e7-945a-67e9c60cf608.png)

**Comment by karanatwal** [comment]
I am using Nexus 5 device. Also i tested on Samsung S7 . i passed "rtmp://rtmp-api.facebook.com:80/rtmp/1694498727277618?ds=1&s_e=4&s_l=1&a=ATgiXVf9LRg8P78s" in `execute("")`

**Comment by mekya** [comment]
It runs on Nexus 5 since the first release. My device is Samsung S5. 

You have used [this guide](https://developers.facebook.com/docs/videos/live-video/getting-started) in creating rtmp url, right?

**Comment by karanatwal** [comment]
Thanx , Issue was in my network . I changed WiFi and now its streaming . Thanx alot for providing support .

**Comment by mekya** [comment]
never mind, it is my pleasure ;)

**Comment by karanatwal** [comment]
@mekya can we record video and save locally while broadcasting ?

**Comment by mekya** [comment]
Actually yeah there is one. We have used it for debugging. It records as a FLV file.

There is file_open and file_close function 
https://github.com/ant-media/LibRtmp-Client-for-Android/blob/master/rtmp-client/src/main/java/net/butterflytv/rtmp_client/RTMPMuxer.java#L44

file_open function is commented out. 
https://github.com/ant-media/LiveVideoBroadcaster/blob/master/liveVideoBroadcasterSDK/src/main/java/io/antmedia/android/broadcaster/network/RTMPStreamer.java#L92

you should call file_close function in close function
https://github.com/ant-media/LiveVideoBroadcaster/blob/master/liveVideoBroadcasterSDK/src/main/java/io/antmedia/android/broadcaster/network/RTMPStreamer.java#L101

**Comment by lordmen99** [comment]
its have lag when streaming?

**Comment by mekya** [comment]
It has just a few milliseconds lag in order to sort some unordered audio and video packets

**Comment by lordmen99** [comment]
u have demo apk? send please

**Comment by mekya** [comment]
Sorry not a demo apk at this time. You need to clone the repo and build your own. 

You may follow this [guide](http://antmedia.io/how-to-develop-a-live-streaming-mobile-app-in-3-steps/) 

Sorry

**Comment by mekya** [comment]
Closing this issue, please feel free to open or comment if you have any problem
