### ISSUE TITLE
Scope vod not found 

### ISSUE THREAD

**Issue by erizokaro** [ant-media/LiveVideoBroadcaster#20]
Can't connect with ant media server using ipv4 192.168.1.40 scope vod not found error.

**Comment by mekya** [comment]
if you use version 1.2.0+, vod scope is not added by default to the ant media server. 

Use "LiveApp" instead of "vod"

**Comment by M7hunter** [comment]
where to put LiveApp

**Comment by mekya** [comment]
closing this issue
