### ISSUE TITLE
start.sh and start.bat does not work

### ISSUE THREAD

**Issue by M7hunter** [ant-media/LiveVideoBroadcaster#22]
when i start this command it says "could not find or load main class org.red5.server.bootstrap"

**Comment by M7hunter** [comment]
i was on windows , so i installed ubuntu and it worked.
but when i press start broadcasting nothing happens .. please help.

**Comment by mekya** [comment]
Are you sure you write the rtmp url correctly and server is running?

Sorry for late reply

**Comment by mekya** [comment]
Closing the issue. Please reopen it if you are having a problem.
