### ISSUE TITLE
Draw HUD/Images on videostream

### ISSUE THREAD

**Issue by havalito** [ant-media/LiveVideoBroadcaster#23]
Hi,

First and foremost really beautiful project and wellwritten code, however I can not seem to grasp where and how I should go about adding my own GUI/HUD to the videostream and not just the display.  Any pointers here?

 Kind regards

**Comment by mekya** [comment]
Hi,

It is a thing about drawing things on OpenGL surface. There is a sample `drawBox()` function in the code. That should be called two places. One of the [CameraSurfaceRenderer](https://github.com/ant-media/LiveVideoBroadcaster/blob/master/liveVideoBroadcasterSDK/src/main/java/io/antmedia/android/broadcaster/encoder/CameraSurfaceRenderer.java#L305) and the other place is [TextureMovieEncoder](https://github.com/ant-media/LiveVideoBroadcaster/blob/master/liveVideoBroadcasterSDK/src/main/java/io/antmedia/android/broadcaster/encoder/TextureMovieEncoder.java#L406).

You can follow the same structure to add extra things. 

I hope I could answer your question. Sorry for late reply and closing this issue. Please feel free to open if it is required for you.
