### ISSUE TITLE
streaming audio only

### ISSUE THREAD

**Issue by alex4well** [ant-media/LiveVideoBroadcaster#25]
can anyone help me please to guide me how to separate audio and video streaming so i can stream audio only...

**Comment by evi8899** [comment]
Hi alex4well,
Did you get any solution to stream audio only? Thanks

**Comment by SelimEmre** [comment]
Hi everyone,

Thank you for your interest. This library is open to development. You can develop your own solution. If you have something to ask, you can mail with us. Mail address is here >> contact@antmedia.io.

**Comment by mekya** [comment]
Closing this issue for the inactivity. Please feel free to re-open  if you are still interested in this issue.

**Comment by alex4well** [comment]
i m still not finding a solution
