### ISSUE TITLE
org.red5.server.net.rtmp.RTMPMinaConnection - Connection is closed: VSNAVMSNLPSGE

### ISSUE THREAD

**Issue by thapachaki** [ant-media/LiveVideoBroadcaster#26]
Hello! When I push "Start Broadcasting" button, the server responds: org.red5.server.net.rtmp.RTMPMinaConnection - Connection is closed: VSNAVMSNLPSGE
org.red5.server.net.rtmp.RTMPMinaIoHandler - Connection was not found for VSNAVMSNLPSGE
My RTMP_BASE_URL is "rtmp://192.168.0.77:1935". What is the problem?
<img width="634" alt="captura de pantalla 2018-04-05 a la s 11 59 10" src="https://user-images.githubusercontent.com/12816865/38377365-c7d8f8b2-38c8-11e8-852a-a0cd9db48f9d.png">
<img width="800" alt="captura de pantalla 2018-04-05 a la s 11 59 35" src="https://user-images.githubusercontent.com/12816865/38377399-d88cf924-38c8-11e8-9949-93847561f09c.png">
![screenshot_20180405-120313](https://user-images.githubusercontent.com/12816865/38377645-6f5f5cac-38c9-11e8-887b-0b82465111df.png)

**Comment by mekya** [comment]
Root app does not accept live streams. 

Please add appname to the RTMP_BASE_URL

Current version of the Ant Media Server has LiveApp by default so you can try the below url.

rtmp://192.168.0.77:1935/LiveApp/

**Comment by thapachaki** [comment]
Thank you very much! It worked!

**Comment by mekya** [comment]
You're welcome. Closing this issue. Please let me know if you have any other problem.

**Comment by devsideal** [comment]
I also getting same issue but this solution not worked for me,
on Start Broadcasting, **getting error "Failed to start. Please check server url and security credentials."**
I already changed the base url in MainActivity to "rtmp://192.168.1.72:1935/vod/"
and also checked with "rtmp://192.168.1.72:1935/LiveApp/" but no luck

My media server status is:

```
sudo service antmedia status
● antmedia.service - LSB: Starts the ant media service
   Loaded: loaded (/etc/init.d/antmedia; bad; vendor preset: enabled)
   Active: active (exited) since Mon 2018-04-09 16:00:18 IST; 38min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 25746 ExecStop=/etc/init.d/antmedia stop (code=exited, status=0/SUCCE
  Process: 25833 ExecStart=/etc/init.d/antmedia start (code=exited, status=0/SUC

Apr 09 16:00:18 devsideal systemd[1]: Starting LSB: Starts the ant media se
Apr 09 16:00:18 devsideal antmedia[25833]: Path /usr/local/antmedia
Apr 09 16:00:18 devsideal antmedia[25833]: Starting the Ant Media Service..
Apr 09 16:00:18 devsideal antmedia[25833]: /etc/init.d/antmedia: 116: ulimi
Apr 09 16:00:18 devsideal antmedia[25833]: The Ant Media Service has starte
Apr 09 16:00:18 devsideal systemd[1]: Started LSB: Starts the ant media ser
```

**Comment by mekya** [comment]
You media service is not running.

It should be "running" instead of "exited". Please let us see the log file log/ant-media-service.log

**Comment by devsideal** [comment]
Thanks, Now its showing "running" and working.

**Comment by alihusseinalissa** [comment]
> Thanks, Now its showing "running" and working.

How did it become running?
I am facing the same problem, the server is active but (exited) and I don't know the season.
