### ISSUE TITLE
can not get the preview on web browser

### ISSUE THREAD

**Issue by tehseensagar** [ant-media/LiveVideoBroadcaster#27]
I've just build the apk and set the 

public static final String RTMP_BASE_URL = "rtmp://x.x.x.x/LiveApp/876369394379275711260742

but can not get the preview on web brower? try to access it via 

http://x.x.x.x:5080/LiveApp/play.html

Getting message on screen:

Stream will start playing automatically when it is live

on android I click on start broadcast it start and creating file on server as well. My question how do I see tihs on web browser directly.

Regards

**Comment by SelimEmre** [comment]
Hi @tehseensagar,

in browser side please try again like this >> http://x.x.x.x/LiveApp/play.html?name=876369394379275711260742
Please let me know if there is any problem. Thank you for your interest. 

Best Regards,
Selim

**Comment by tehseensagar** [comment]
@SelimEmre  Thanks a lot, I observed a delay can it be minimized . It's around 30 sec delay for next frame. 

Regards

**Comment by Krishna1238** [comment]
How to install Ant media server in Windows for Android .? Can you explain thes steps to generate these URL. 
public static final String RTMP_BASE_URL = "rtmp://192.168.6.70/LiveApp/";

**Comment by davutcavdar** [comment]
@Krishna1238 Ant Media Server, unfortunately, does not run on Windows. Please use Ubuntu instances to use it.

Closing this issue, if you have new issues please open new ones.
