### ISSUE TITLE
start.sh file not run properly

### ISSUE THREAD

**Issue by hmskhan** [ant-media/LiveVideoBroadcaster#30]
Hello Dear,
**start.sh** file not run proper as you written. When I run this file so command window was open and close in 1 second.
Please help me.
Thanks !!!

**Comment by bykeat** [comment]
I was caught into same issue using start-debug.sh too. [https://drive.google.com/file/d/119SEA4dIGnnCawdaq7JOjwIjGBU6kO7n/view?usp=sharing](url)

**Comment by davutcavdar** [comment]
You seem to use MinGW instance. Unfortunately, Ant Medi Server does not run
on that. Please use Ubuntu instance instead.

Davut ÇAVDAR, M.Sc


2018-08-13 9:08 GMT+03:00 bykeat <notifications@github.com>:

**Comment by bykeat** [comment]
@davutcavdar I had tried on Ubuntu 16.04 LTS. Still hit the same error.

Screenshot:
https://drive.google.com/open?id=1pyT89sNO2MSiN-qC1EbR9TftMcujt6nM

Both node I ran under JDK1.8.0_181 please advice what can I do to resolve this issue.

**Comment by mekya** [comment]
One point, do you run in the server folder? 
`
./start.sh
`

**Comment by mekya** [comment]
You're doing correctly. 

I think there should be some another thing on your instance.  Is there a way that we can connect remotely and find out what is going there.

Regards,
A. Oguz

**Comment by bykeat** [comment]
Hi @mekya,

Do let me know when you want to access the PC. I will turn it on. Please be informed that my timezone here is GMT +8.

**Comment by mekya** [comment]
Hi @bykeat 

I have sometime for that now. May I access now?

**Comment by bykeat** [comment]
Hi @mekya,

I have turned it on now for 8 hours in my office until 5pm (GMT +8). Then will continue to let it on after I get home after 7pm (GMT +8).

**Comment by mekya** [comment]
yeah it works on ubuntu and mac. Windows is not supported. 

Closing this issue. Please re-open it if you have any question.
