### ISSUE TITLE
Changing Orientation Stops the Broadcast and Gives Blank Video of Recorded

### ISSUE THREAD

**Issue by sraja415** [ant-media/LiveVideoBroadcaster#31]
If I change the orientation, the broadcast video stops with error and what ever was broadcast till such time shows blank in recorded.

**Comment by mekya** [comment]
Yeah you are right.  I've sent an new commit for this.  Could you please try?

Secondly, orientation changes actually affects aspect ratio. So it is not very common to change codec configuration while playing. I mean, for instance while streaming resolutions is not changed to 640x360 from 360x640.  

It is good to lock the orientation while in streaming.

**Comment by mekya** [comment]
Issues tab will be closed for this project. Please submit your issues on https://github.com/ant-media/Ant-Media-Server
