### ISSUE TITLE
Audio Mute/UnMute

### ISSUE THREAD

**Issue by rajkumariparihar** [ant-media/LiveVideoBroadcaster#32]
Hi,  can you please help me,  how I can implement mute/unmute audio in live broadcast streaming. So that user can mute audio, if s/he don't want audio to be stream with video in Live.

Thanks! Looking forward for solution,

**Comment by AlexUrrutia** [comment]
+1

**Comment by LSDsl** [comment]
+1

**Comment by Stmf** [comment]
LiveVideoBroadcaster.java
audioThread = new AudioRecorderThread(SAMPLE_AUDIO_RATE_IN_HZ, **0**, audioHandler);

**Comment by mekya** [comment]
Issues tab will be closed for this project. Please submit your issues on https://github.com/ant-media/Ant-Media-Server
