### ISSUE TITLE
 Network Connectivity drop Issues stops the stream and recorded video also does not come

### ISSUE THREAD

**Issue by sraja415** [ant-media/LiveVideoBroadcaster#33]
Lets say I loose my network connectivity for a few seconds the stream stops.What I streamed thus far also does not get recorded. 

1. It should actually Pause and wait for re-establishment
2. Even if it stops, the video I streamed thus far should be recorded instead of some bland video.

**Comment by mekya** [comment]
Issues tab will be closed for this project. Please submit your issues on https://github.com/ant-media/Ant-Media-Server
