### ISSUE TITLE
Minimize App stops stream

### ISSUE THREAD

**Issue by sraja415** [ant-media/LiveVideoBroadcaster#34]
If I minimize the app while streaming, the streaming stops. It should act as 
1. Prefer to Pause
2. Else continue to stream.

Why would i do that?
- To share the stream via Messaging apps.
- Because I got an important message.

**Comment by mekya** [comment]
Issues tab will be closed for this project. Please submit your issues on https://github.com/ant-media/Ant-Media-Server
