### ISSUE TITLE
Streaming to youtube doesn't work

### ISSUE THREAD

**Issue by maniacs-engineerica** [ant-media/LiveVideoBroadcaster#37]
Hi, thanks for your share your work to the community.

I am trying to stream to youtube, but something is not working. The code seems to work fine, but when I go to my event in Youtube it doesn't show anything.

Thanks,
Matias.

**Comment by mekya** [comment]
Issues tab will be closed for this project. Please submit your issues on https://github.com/ant-media/Ant-Media-Server
