### ISSUE TITLE
Stream not publishing after camera switch

### ISSUE THREAD

**Issue by Lethea** [ant-media/LiveVideoBroadcaster#38]
Device : Note 5
Os : Android 7.0
Scenario 1 : Publisher fill the box and start streaming, switch camera, the stream freeze a few sec in watcher screen, then start to play
Scenario 2 : Publisher  fill the box and start streaming, switch camera,no problem, after 3-4 switch the scenario 1 occurs
Scenario 3 : Publisher  fill the box and start streaming, switch camera, the stream closed and does not start stream again without pressing stop / publish button

**Comment by mekya** [comment]
Issues tab will be closed for this project. Please submit your issues on https://github.com/ant-media/Ant-Media-Server
