### ISSUE TITLE
[Question] About frameRate.

### ISSUE THREAD

**Issue by EkslV** [ant-media/LiveVideoBroadcaster#39]
Hi. I make tests of LiveVideoBroadcaster. I don`t understand why fps is around 20. I changed it in lot of classes as LiveVideoBroadcaster.java, CameraSurfaceRenderer.java, TextureMovieEncoder.java. I checked that bestFps that used in setPreviewFpsRange - 30000. But it still around 20, how I can change it to 30?

**Comment by mekya** [comment]
Issues tab will be closed for this project. Please submit your issues on https://github.com/ant-media/Ant-Media-Server
