### ISSUE TITLE
Unable to start stream

### ISSUE THREAD

**Issue by get2abhi** [ant-media/LiveVideoBroadcaster#41]
getting result = -3 when opening rtmpStreamer.open(url)

![image](https://user-images.githubusercontent.com/2540446/47648198-53fa5d80-db9f-11e8-8816-5d4378e4a46a.png)

**Comment by mekya** [comment]
Issues tab will be closed for this project. Please submit your issues on https://github.com/ant-media/Ant-Media-Server
