### ISSUE TITLE
Failed to start. Please check server url and security credentials.

### ISSUE THREAD

**Issue by jpratik** [ant-media/LiveVideoBroadcaster#42]
I have uploaded community server on aws server and it's work fine, I am able to create live stream and webrtcapp stream from server admin but while pasting url for streaming with rtmp in android app it's always shows the error mentioned in title. I have checked different url like adding www,  using http instead of rtmp but doesn't work at all.while creating stream from admin giving me link with rtmp that link also doesn't work in app. please let me know what changes I have to do

**Comment by thesuraj** [comment]
Waiting for solution. Even I am getting the same error.

**Comment by haseebpvt** [comment]
@thesuraj @jpratik Solved it? I'm facing the same problem.

**Comment by mekya** [comment]
are you sure that rtmp server port 1935 open and you write the server url correctly in the code?

**Comment by AbdulMalik206267** [comment]
Hi all,
I have been working on live broadcast feature since last two months and it worked perfectly ok then and now when I try to broadcast video it gives me the same error. Is there someone who has resolved this issue?

**Comment by AlexUrrutia** [comment]
What error?

**Comment by AbdulMalik206267** [comment]
@AlexUrrutia I am not using any server but I get rtmp stream url from facebook graph api and pass it to the LiveBroadCaster where it starts broad casting live video on facebook page.

**Comment by AbdulMalik206267** [comment]
The issue that I figured out is that I was using rtmp url before and now to broadcast video on Facebook you have to use rtmps (secure stream url).  Does it mean that this broad caster only works for rtmp but not for rtmps.

**Comment by mekya** [comment]
Issues tab will be closed for this project. Please submit your issues on https://github.com/ant-media/Ant-Media-Server
