### ISSUE TITLE
After Camera switch half of the screen gets blurred

### ISSUE THREAD

**Issue by anujyadav2705** [ant-media/LiveVideoBroadcaster#46]
While doing the livestream, if I switch the camera then half of the screen becomes blurred. Attached are the screen shot.
![screenshot](https://user-images.githubusercontent.com/44973353/52061442-4edcee00-2594-11e9-9675-23d777efdb11.png)
![screenshot1](https://user-images.githubusercontent.com/44973353/52061443-4f758480-2594-11e9-9343-b1ab3559c984.png)

**Comment by mekya** [comment]
Issues tab will be closed for this project. Please submit your issues on https://github.com/ant-media/Ant-Media-Server
