### ISSUE TITLE
How could find LiveVideoBroadcaster documents?

### ISSUE THREAD

**Issue by WenqiangXieIgg** [ant-media/LiveVideoBroadcaster#48]
I want to set RTMP player less buff to make low delay, but I can't find documents. How could do this?

**Comment by SelimEmre** [comment]
Hi @WenqiangXie,
You can try Ant Media Server Community Edition for RTMP delay. We prepared Tutorial video instead of documentation. Please review video tutorial https://www.youtube.com/watch?v=-azHuHdqBbE

If you have any detail question, please feel free to ask contact@antmedia.io 

Thanks,
Selim

**Comment by mekya** [comment]
Issues tab will be closed for this project. Please submit your issues on https://github.com/ant-media/Ant-Media-Server
