### ISSUE TITLE
start broadcasting buttoon

### ISSUE THREAD

**Issue by lordmen99** [ant-media/LiveVideoBroadcaster#5]
Its not working when press start broadcasting button

**Comment by mekya** [comment]
Hmm, please check the below items

- Have you set server ip address correctly in the app?
- Have you started the server?
- Mobile device can reach the server directly via ip network? 

If everything is ok, please let me know your device and android version in addition please send the log of the app and the server

**Comment by mekya** [comment]
No default ip does not work. Please follow this guide.

https://antmedia.io/how-to-develop-a-live-streaming-mobile-app-in-3-steps/

**Comment by lordmen99** [comment]
can u give ur ip for me to test demo this app

**Comment by mekya** [comment]
There is no public demo server to test this app. 

Nevertheless, send me an email and will going to arrange something for you 

mekya at antmedia dot io

**Comment by lordmen99** [comment]
dnang99@gmail.com

**Comment by lordmen99** [comment]
working.. btw, how make list room and any user can join and leave room

**Comment by mekya** [comment]
Just a kind of web app should be developed in order to do this. 
We may support on you in developing this app.

**Comment by lordmen99** [comment]
i can stream, but how i can join the channel stream? i cant see broadcaster stream when click player..

**Comment by mekya** [comment]
You need to enter the stream key with "live=1" parameter in order to play live stream

For instance, if you broadcast live stream from one device with stream name "test63jd7"
then open live video player in another device and enter "test63jd7 live=1" then 
press play button.

**Comment by Anjalitripathi** [comment]
Hi mekya,

I am facing some difficulty to set server to test app. Can you please help or arrange some demo server so I can test your app. Below is my email praveen.mishra@systematixindia.com

**Comment by mekya** [comment]
Do you have any update @lordmen99 ?

**Comment by lordmen99** [comment]
yes  working, but quality video not clear and not smooth? what cause this

**Comment by mekya** [comment]
You can change the quality by changing resolution. You can do that by using the settings  button on the left top corner in the demo app. 


![](https://camo.githubusercontent.com/06d02fa369bbce9f6f5951249f26b262797796e4/687474703a2f2f616e746d656469612e696f2f77702d636f6e74656e742f75706c6f6164732f323031372f30342f7265636f72642d65313439323335323638373838332e706e67)

**Comment by lordmen99** [comment]
about live streaming cost? how much for month? and how setupfrom aws
marketplace

**Comment by mekya** [comment]
If you use images on Amazon AWS, it is a little bit more expensive. 
If you purchase support directly from us, we provide enterprise edition and support for 19 usd per month, 199 usd per year. This price is going to be higher in coming weeks with new enterprise release.

The other costs are AWS EC2 prices and data cost.

If it is ok for you, we can continue on this talk via e-mail  mekya@antmedia.io

**Comment by yf13** [comment]
Does this work with NGINX rtmp module? I can stream to NGINX using ffmpeg and see results using ffplay.... however, this app can't stream to NGINX.

**Comment by M7hunter** [comment]
how the button worked .. i have the same issue .. please help.

**Comment by mekya** [comment]
Closing this issue for the inactivity. Please re-open it if you are having problems.
