### ISSUE TITLE
Unable to detect RTMP Url

### ISSUE THREAD

**Issue by namespace7** [ant-media/LiveVideoBroadcaster#50]
i have created a local nginx server on ubuntu machine, and have connected my android phone into the same wifi network and try Starting the broadcasting , however the application is not able to detect the Ip Address!!

how do i know whether my nginx server is working?
-> i'm able to play stream sent by ffmpeg
**ffmpeg -re -i video.mp4 -c copy -f flv rtmp://localhost/mystream**
What Url i'm using in the android application?
-> since both my android and linux  server system is in same network and my server's local ip is - 10.18.10.21
so ** public static final String RTMP_BASE_URL = "rtmp://10.18.10.21/mystream"**
what's the error?? 
suggestion will be appreciated!

**Comment by mekya** [comment]
Issues tab will be closed for this project. Please submit your issues on https://github.com/ant-media/Ant-Media-Server
