### ISSUE TITLE
Audio off

### ISSUE THREAD

**Issue by dksush** [ant-media/LiveVideoBroadcaster#51]
hi
im using rtmp and webrtc sdk(enterprise version) on android.

rtmp publisher -> webrtc receiver(mode_play)
i want to turn off the sound of webrtc player video.

When I send video&audio to rtmp, can I send video only?(no audio) 

could i get some advice?

**Comment by mekya** [comment]
Issues tab will be closed for this project. Please submit your issues on https://github.com/ant-media/Ant-Media-Server
