### ISSUE TITLE
Live Broadcasting crashes when broadcasting more than 2 mins

### ISSUE THREAD

**Issue by ramiz272** [ant-media/LiveVideoBroadcaster#52]
Broadcasting crashes after gone live for couple of mins. 
Following errors were displayed in logkat:

2019-05-20 16:35:03.351 7999-7999/io.antmedia.android.livevideopublisher E/HW-JPEG-DEC: [HME_JPEG_DEC_Delete](3321): HME_JPEG_DEC_Delete: decoder_ctx=null 
E/BufferQueueProducer: [SurfaceTexture-1-7999-0] cancelBuffer: BufferQueue has been abandoned 
E/Camera: Camera new cameraInitNormal:0 

Please provide the fix or let me know how to fix this
Thanks,
Ramiz

**Comment by mekya** [comment]
Issues tab will be closed for this project. Please submit your issues on https://github.com/ant-media/Ant-Media-Server
