### ISSUE TITLE
Signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x30

### ISSUE THREAD

**Issue by nguyenduyphuonghh** [ant-media/LiveVideoBroadcaster#55]
Hello admin,
I'm using your demo to publish live stream, it worked great on my xiaomi 4 LTE. But I got this crash message on other devices (xiaomi redme note 3, mi 8 lite, samsung a9 2018):

* * * * * * * * * * * * * * * *
Build fingerprint: 'Xiaomi/hennessy/hennessy:5.0.2/LRX22G/V9.6.1.0.LHNCNFD:user/release-keys'
Revision: '0'
ABI: 'arm64'
pid: 1439, tid: 10315, name: TextureMovieEnc  >>> io.antmedia.android.liveVideoBroadcaster <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x30
    x0   0c3fffffffffffff  x1   0000007f66fc01f0  x2   0000000000000001  x3   0002000200080000
    x4   0000000000000003  x5   0800100004000002  x6   0000007f66fc02ec  x7   000000558fdd2e48
    x8   000000558fee9eb0  x9   000000558ff667d0  x10  0000000000000000  x11  0000000000000000
    x12  0000000000000000  x13  000000558fee9a40  x14  000000558ff447e8  x15  000000558fdd2e78
    x16  0000000000000000  x17  0000000000000004  x18  000000558feea360  x19  000000558fed1280
    x20  000000558fdd49f0  x21  0000000000000030  x22  000000558fdd2e78  x23  000000558fdd2d80
    x24  0000000000000002  x25  000000558feea77c  x26  0000000000000001  x27  000000558ff667d0
    x28  000000558fee6360  x29  0000007f66fc01b0  x30  0000007f757fe86c
    sp   0000007f66fc01b0  pc   0000007f757fe884  pstate 0000000080000000

backtrace:
    #00 pc 0000000000074884  /system/vendor/lib64/egl/libGLESv2_mtk.so
    #01 pc 0000000000075284  /system/vendor/lib64/egl/libGLESv2_mtk.so
    #02 pc 0000000000089884  /system/vendor/lib64/egl/libGLESv2_mtk.so
    #03 pc 0000000000020ed0  /system/vendor/lib64/egl/libGLESv2_mtk.so (glDrawArrays+688)
    #04 pc 0000000000dead48  /data/dalvik-cache/arm64/system@framework@boot.oat
<hr><br>
Please help me!<br>
Thanks.

**Comment by mekya** [comment]
Issues tab will be closed for this project. Please submit your issues on https://github.com/ant-media/Ant-Media-Server
