### ISSUE TITLE
Integration in another app

### ISSUE THREAD

**Issue by blaze021** [ant-media/LiveVideoBroadcaster#56]
I tried to integrate this app into my own app for more functionalities so integrated it ,but when i tried to run it only broadcasting was working while when i hit the play button in the videoplayer(ExoPlayer) it suddenly crashed and i was moved to the previous activity.

I built it with an authentication using FirebaseAuth, but I don't think it should cause any big issues.
If you know anything about the issue then please help.
I can provide you with the code if you want.

**Comment by mekya** [comment]
Issues tab will be closed for this project. Please submit your issues on https://github.com/ant-media/Ant-Media-Server
