### ISSUE TITLE
mLiveVideoBroadcaster.startBroadcasting is returning null in doInBackground

### ISSUE THREAD

**Issue by Yesha052** [ant-media/LiveVideoBroadcaster#57]

**Comment by Yesha052** [comment]
@Override
                                                protected Boolean doInBackground(String... url) {

                                                    return mLiveVideoBroadcaster.startBroadcasting(url[0]);


                                                }

In Above code, I am getting null. So VideoBroad cast is not started. Please help me ASAP. Its urgent.

**Comment by mekya** [comment]
Issues tab will be closed for this project. Please submit your issues on https://github.com/ant-media/Ant-Media-Server
