### ISSUE TITLE
screen shot streaming

### ISSUE THREAD

**Issue by Zouzoufa** [ant-media/LiveVideoBroadcaster#6]
hello,
i would like to ask you if there's any ay to publish my screen shot to the server
thx

**Comment by mekya** [comment]
This is almost what we plan to do. We plan to create a webrtc app that can stream camera and screen to the server. One is sponsor for this app however they postponed this sponsorship so I think our implementation is likely to wait this sponsorship.

**Comment by mekya** [comment]
Issues tab will be closed for this project. Please submit your issues on https://github.com/ant-media/Ant-Media-Server
