### ISSUE TITLE
how to stretch video?

### ISSUE THREAD

**Issue by Kristaps89** [ant-media/LiveVideoBroadcaster#8]
After integrating your SDK into my app, I can see that there is option to set screen resolution, for example, 1072*1072, 720*480...
The problem is when i set any of them, it does stretch to screen.
But I want aspect fit to screen.
Is there any options to set content mode to Aspect Fit?
I need your urgent help,
Thanks

**Comment by mekya** [comment]
Hi
There is a class for this. 
Comment out this lines
https://github.com/ant-media/LiveVideoBroadcaster/blob/master/app/src/main/res/layout/activity_live_video_broadcaster.xml#L9

get the view by findViewById(R.id.cameraPreview_afl)

then call setAspectRatio function
http://google.github.io/ExoPlayer/doc/reference-v1/com/google/android/exoplayer/AspectRatioFrameLayout.html#setAspectRatio-float-

Let me know if it does not work for you

**Comment by mekya** [comment]
Closing this issue for the inactivity.
