### ISSUE TITLE
Getting IO Exception while playing live video

### ISSUE THREAD

**Issue by mrunalBadujar** [ant-media/LiveVideoBroadcaster#9]
10-04 16:17:42.861 4113-7516/com.offerclout.offermania W/System.err: net.butterflytv.rtmp_client.RtmpClient$RtmpIOException
10-04 16:17:42.861 4113-7516/com.offerclout.offermania W/System.err:     at net.butterflytv.rtmp_client.RtmpClient.open(RtmpClient.java:55)
10-04 16:17:42.861 4113-7516/com.offerclout.offermania W/System.err:     at com.offerclout.offermania.utils.RtmpDataSource.open(RtmpDataSource.java:44)
10-04 16:17:42.861 4113-7516/com.offerclout.offermania W/System.err:     at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:631)
10-04 16:17:42.861 4113-7516/com.offerclout.offermania W/System.err:     at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
10-04 16:17:42.861 4113-7516/com.offerclout.offermania W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
10-04 16:17:42.861 4113-7516/com.offerclout.offermania W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
10-04 16:17:42.861 4113-7516/com.offerclout.offermania W/System.err:     at java.lang.Thread.run(Thread.java:818)

**Comment by davutcavdar** [comment]
This issue is probably about your network configuration.

Update: You have mailed and updated that this issue is resolved.
